#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x50FE47277DC196FB (thurston@cs.queensu.ca)
#
Name     : ragel
Version  : 6.10
Release  : 1
URL      : https://www.colm.net/files/ragel/ragel-6.10.tar.gz
Source0  : https://www.colm.net/files/ragel/ragel-6.10.tar.gz
Source99 : https://www.colm.net/files/ragel/ragel-6.10.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: ragel-bin
Requires: ragel-doc
BuildRequires : go
BuildRequires : ruby

%description
======================================
1. Build Requirements
---------------------

%package bin
Summary: bin components for the ragel package.
Group: Binaries

%description bin
bin components for the ragel package.


%package doc
Summary: doc components for the ragel package.
Group: Documentation

%description doc
doc components for the ragel package.


%prep
%setup -q -n ragel-6.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522114180
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522114180
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ragel

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/ragel/*
%doc /usr/share/man/man1/*
